name: Integration

on:
  workflow_dispatch: {}
  push:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  linting:
    uses: ./.github/workflows/setup-and-cache.yml
    with:
      python-version: '3.12'

    steps:
      - name: Check Code Style
        run: black --check .

  run-tests:
    uses: ./.github/workflows/setup-and-cache.yml
    with:
      python-version: '3.12'

    steps:
      - name: Run Tests
        run: poetry run pytest
